### ISSUE TITLE
feat: remove dependency on js-ipfs

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipld-explorer-components#359]
```[tasklist]
### Tasks
- [x] investigate getting blocks/cars using gateway-api, (playground for work required to decouple data-transfer method in helia)
- [x] Talked with Alex, a simple dag-method wrapper method could be a simpler and more decentralized approach
- [x] use kubo-rpc-client instead of ipfs-http-client
```

**Comment by BigLep** [comment]
@SgtPooki : a couple of thoughts:
1. Do we maybe want to start building out a "client library" for hitting the Trustless HTTP Gateway API for getting blocks and cars.  My guess is dotStorage has likely already created this in some form?  @lidel may also know of other cases of this being created in JS already.
2. What is Kubo specific about ipld-explorer-components?  I'm basically wondering why we even need a dependency on kubo-rpc-client.

**Comment by lidel** [comment]
- We should not use any RPC library here.  There is nothing specific about Kubo or JS-IPFS
- The only interface this app needs is a function that takes a CID and returns bytes for a single block, all parsing happens in JS in the browser (self-contained).
  - the block can be [fetched from a trustless gateway](https://docs.ipfs.tech/reference/http/gateway/#trustless-verifiable-retrieval) as  [application/vnd.ipld.raw](https://www.iana.org/assignments/media-types/application/vnd.ipld.raw)
  - or be fetched via Helia instance

**Comment by SgtPooki** [comment]
> For this app specifically, (diagnostic tool that slowly fetches small chunk of DAG), i advise against CARs, and do block-by-block

There is already some CAR logic in there, so i assume you're talking about fetching blocks instead of fetching CARs 

> A single block can be fetched:

I've got this mostly done now, where I query with helia first, with a 5sec timeout, and then query with the trustless gateway.

> Prior art for this exists in Peers screen of ipfs-webui (https://www.npmjs.com/package/ipfs-geoip fetches raw blocks from HTTP gateway and does all parsing in JS – [see code here](https://github.com/ipfs-shipyard/ipfs-geoip/blob/466cd9d6454098c0fcf998b2217225099a654695/src/lookup.js#L18))

It looks like the geoip code is not validating the blocks after retrieving? There isn't any info at https://docs.ipfs.tech/reference/http/gateway/#example-fetching-a-single-raw-block-from-a-public-gateway on how to do that, but I think it's something like:

1. have CID instance (with codec type and whatnot)
2. fetch raw block
3. construct CID using raw block bytes, using multihash+codec+base+cidVersion from CID instance in step 1 above.
4. ensure step 1 CID.toString() matches step3 CID.toString()  ?

**Comment by BigLep** [comment]
Thanks @SgtPooki .  Looking forward to seeing the PR here.

For your last question, if you're getting blocked, I would post in #ip-js.  I expect various folks can point to the JS way of doing block validation.

**Comment by SgtPooki** [comment]
FYI: the verify block functionality is handled by https://github.com/ipfs/ipld-explorer-components/blob/09ab5e813ff38395528ae3ca798e0d7b1e1dea70/src/lib/get-raw-block.ts#L51
